server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://entity-display-api:8003/api/;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding off;
    }

    location = /landing {
        proxy_pass http://entity-display-api:8003/landing;
        proxy_http_version 1.1;
    }

    location /api/portal/ {
        proxy_pass http://entity-display-api:8003/api/portal/;
        proxy_http_version 1.1;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
